<a href="https://colab.research.google.com/github/BKnightHD/MS-Data-Science/blob/main/M3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def testIfPartitioned(a, k):
    assert 0 <= k < len(a)

    left = a[:k]
    right = a[k+1:]

    for i in left:
        if i > a[k]:
            return False

    for i in right:
        if i <= a[k]:
            return False
    return True

In [ ]:
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 14, 10, 23],5) == True, ' Test # 1 failed.'
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 14, 11, 23],4) == False, ' Test # 2 failed.'
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 14, 23, 21],0) == True, ' Test # 3 failed.'
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 14, 22, 23],9) == True, ' Test # 4 failed.'
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 14, 8, 23],5) == False, ' Test # 5 failed.'
assert testIfPartitioned([-1, 5, 2, 3, 4, 8, 9, 13, 9, -11],5) == False, ' Test # 6 failed.'
assert testIfPartitioned([4, 4, 4, 4, 4, 8, 9, 13, 9, 11],4) == True, ' Test # 7 failed.'
print('Passed all tests (10 points)')

Passed all tests (10 points)


In [ ]:
def swap(a, i, j):
    assert 0 <= i < len(a), f'accessing index {i} beyond end of array {len(a)}'
    assert 0 <= j < len(a), f'accessing index {j} beyond end of array {len(a)}'
    a[i], a[j] = a[j], a[i]

def tryPartition(a):
    # implementation of Lomuto partitioning algorithm
    n = len(a)
    pivot = a[n-1] # choose last element as the pivot.
    i,j = 0,0 # initialize i and j both to be 0
    for j in range(n-1): # j = 0 to n-2 (inclusive)
        # Invariant: a[0] .. a[i] are <= pivot
        #            a[i+1]...a[j-1] are > pivot
        if a[j] <= pivot:
            swap(a, i+1, j)
            i = i + 1
    swap(a, i+1, n-1) # place pivot in its correct place.
    return i+1 # return the index where we placed the pivot

In [ ]:
# Write an array called a1 that will be incorrectly partitioned by the tryPartition algorithm above
# Your input when run on tryPartition algorithm should raise an out of bounds array access exception
# in the swap function or fail to partition correctly.

## Define an array a1 below of length > 0 that will be incorrectly partitioned by tryPartition algorithm.
## We will test whether your solution works in the subsequent cells.
# your code here
a1 = [-1, 5, 2, 3, 4, 8, 9, 14, 10, 23]
assert(len(a1) > 0)

# Write an array called a2 that will be incorrectly partitioned by the tryPartition algorithm above
# Your input when run on tryPartition algorithm should raise an out of bounds array access exception
# in the swap function or fail to partition correctly.
# a2 must be different from a1

# your code here
a2 = [-1, 5, 2, 3, 4, 8, 9, 14, 10, 24]
assert( len(a2) > 0)
assert (a1 != a2)


# Write an array called a3 that will be incorrectly partitioned by the tryPartition algorithm above
# Your input when run on tryPartition algorithm should raise an out of bounds array access exception
# in the swap function or fail to partition correctly.
# a3 must be different from a1, a2

# your code here
a3 = [-1, 5, 2, 3, 4, 8, 9, 14, 10, 25]
assert( len(a3) > 0)
assert (a3 != a2)
assert (a3 != a1)

def dummyFunction():
    pass


In [ ]:
# your code here

In [ ]:
try:
    j1 = tryPartition(a1)
    assert not testIfPartitioned(a1, j1)
    print('Partitioning was unsuccessful - this is what you were asked to break the code')
except Exception as e:
    print(f'Assertion failed {e} - this is fine since you were asked to break the code.')

try:
    j2 = tryPartition(a2)
    assert not testIfPartitioned(a2, j2)
except Exception as e:
    print(f'Assertion failed {e} - this is fine since you were asked to break the code.')


try:
    j3 = tryPartition(a3)
    assert not testIfPartitioned(a3, j3)
except Exception as e:
    print(f'Assertion failed {e} - this is fine since you were asked to break the code.')

dummyFunction()

print('Passed 5 points!')

Assertion failed accessing index 10 beyond end of array 10 - this is fine since you were asked to break the code.
Assertion failed accessing index 10 beyond end of array 10 - this is fine since you were asked to break the code.
Assertion failed accessing index 10 beyond end of array 10 - this is fine since you were asked to break the code.
Passed 5 points!


In [ ]:
from random import random

def dot_product(lst_a, lst_b):
    and_list = [elt_a * elt_b for (elt_a, elt_b) in zip(lst_a, lst_b)]
    return 0 if sum(and_list)% 2 == 0 else 1

def matrix_multiplication(H, lst):
    results = []
    for row in H:
        and_list = [elt_a * elt_b for (elt_a, elt_b) in zip(row, lst)]
        results.append(0 if sum(and_list) % 2 == 0 else 1)
    return results

In [ ]:
A1 = [[0,1,0,1],[1,0,0,0],[1,0,1,1]]
b1 = [1,1,1,0]
c1 = matrix_multiplication(A1, b1)
print('c1=', c1)
assert c1 == [1,1,0] , 'Test 1 failed'

A2 = [ [1,1],[0,1]]
b2 = [1,0]
c2 = matrix_multiplication(A2, b2)
print('c2=', c2)
assert c2 == [1, 0], 'Test 2 failed'

A3 = [ [1,1,1,0],[0,1,1,0]]
b3 =  [1, 0,0,1]
c3 = matrix_multiplication(A3, b3)
print('c3=', c3)
assert c3 == [1, 0], 'Test 3 failed'

c1= [1, 1, 0]
c2= [1, 0]
c3= [1, 0]


In [ ]:
import numpy as np
def return_random_hash_function(m, n):
  x = np.random.choice([1,0], p=[0.5, 0.5], size=(m, n))
  return x
    # return a random hash function wherein each entry is chosen as 1 with probability >= 1/2 and 0 with probability < 1/2
    # your code here

H = return_random_hash_function(5,4)
print('H=', H)
assert len(H) == 5, 'Test 5 failed'
assert all(len(row) == 4 for row in H), 'Test 6 failed'
assert all(elt == 0 or elt == 1 for row in H for elt in row ),  'Test 7 failed'

H2 = return_random_hash_function(6,3)
print('H2=', H2)
assert len(H2) == 6, 'Test 8 failed'
assert all(len(row) == 3 for row in H2),  'Test 9 failed'
assert all(elt == 0 or elt == 1 for row in H2 for elt in row ), 'Test 10 failed'
print('Tests passed: 10 points!')

H= [[1 0 1 0]
 [0 0 1 0]
 [0 0 1 0]
 [1 0 1 1]
 [1 0 0 1]]
H2= [[0 1 1]
 [0 1 0]
 [1 1 1]
 [0 1 1]
 [1 1 1]
 [0 1 0]]
Tests passed: 10 points!
